### ISSUE TITLE
Django 4.1 incompatibility

### ISSUE THREAD

**Issue by danjac** [netzkolchose/django-fast-update#14]
Looks like Django 4.1 is incompatible with django-fast-update:

```
 Because django-fast-update (0.2.0) depends on Django (>=3.2,<4.1)
   and no versions of django-fast-update match >0.2.0,<0.3.0, django-fast-update (>=0.2.0,<0.3.0) requires Django (>=3.2,<4.1).

```

**Comment by jerch** [comment]
This is mainly a safety measure, have to test first, if things keep working under django 4.1 and do another release.

Thx for the headsup.

**Comment by jerch** [comment]
@danjac Updated package version to 0.2.1.
