### ISSUE TITLE
Hard-coded dependency breaks Django minor and patch updates

### ISSUE THREAD

**Issue by danjac** [netzkolchose/django-fast-update#19]
Django 4.2.1 was updated recently with a security patch

https://docs.djangoproject.com/en/4.2/releases/4.2.1/

However, when upgrading to latest Django using Poetry, this breaks compatibility with `django-fast-update`:

`django-fast-update (0.2.2) depends on Django (>=3.2,<=4.2)`

It looks like the dependency is set for some reason to upper limit of 4.2, which does not allow minor/patch updates, including security patches.

**Comment by jerch** [comment]
Hmm, what would you suggest? Is `<5.0` reasonable, given that django typically jumps to next major after last LTS relase?

**Comment by danjac** [comment]
Perhaps just `>=3.2` ? i.e. no need to set the upper dependency limit

**Comment by jerch** [comment]
Yeah, thats fine by me, gonna remove the upper restriction...
